2021-11-24 23:11:43.108 | DEBUG    | __main__:_test_query_all_stock:20 - this is a debug message
2021-11-24 23:11:43.108 | INFO     | __main__:_test_query_all_stock:21 - this is a info message
2021-11-24 23:18:02.996 | INFO     | __main__:my_send_mail:36 - send email success
2021-11-24 23:21:04.936 | INFO     | utils.message_utils:my_send_mail:34 - send email success
2021-11-24 23:45:53.893 | ERROR    | __main__:<module>:68 - An error has been caught in function '<module>', process 'MainProcess' (3155), thread 'MainThread' (4669935104):
Traceback (most recent call last):

> File "/Users/xiangfeng/PycharmProjects/my_stock/my_run.py", line 68, in <module>
    send_wechat_msg("hello world")
    └ <function send_wechat_msg at 0x7fb4b727d670>

  File "/Users/xiangfeng/PycharmProjects/my_stock/utils/message_utils.py", line 49, in send_wechat_msg
    a = 1 / 0

ZeroDivisionError: division by zero
2021-11-24 23:47:23.476 | ERROR    | __main__:<module>:68 - An error has been caught in function '<module>', process 'MainProcess' (3176), thread 'MainThread' (4406406656):
Traceback (most recent call last):

> File "/Users/xiangfeng/PycharmProjects/my_stock/my_run.py", line 68, in <module>
    send_wechat_msg("hello world")
    └ <function send_wechat_msg at 0x7f971d17c670>

  File "/Users/xiangfeng/PycharmProjects/my_stock/utils/message_utils.py", line 54, in send_wechat_msg
    a = 1 / 0

ZeroDivisionError: division by zero
2021-11-24 23:48:13.599 | INFO     | utils.message_utils:send_wechat_msg:57 - send wechat fail
2021-11-24 23:58:39.815 | INFO     | __main__:_test_plot_candlestick_from_jq:45 - 成功保存K线图
